# Generated by Django 5.0.7 on 2024-08-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_article_content_alter_article_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tittle',
            new_name='title',
        ),
    ]
