# Generated by Django 4.0.6 on 2024-07-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_remove_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
